### ISSUE TITLE
Issue: Loading video for annotation

### ISSUE THREAD

**Issue by jgamamonteiro** [biigle/core#513]
## Version: v3.45.0

```yml
biigle/ananas: v1.15.1
biigle/color-sort: v2.12.1
biigle/geo: v1.21.1
biigle/laravel-file-cache: v4.0.1
biigle/largo: v2.27.0
biigle/laserpoints: v2.17.2
biigle/reports: v4.28.2
biigle/sync: v2.4.2
```

### Issue: 
We are currently setting up a local instance in our server to use Biigle from our network. We have ROV and Submarine videos for annotation. ROV small cameras (`PARALENZ`) produce mp4 files with around `4GB` and `MP41` codec. We have no issues loading these files. However, our larger files from bigger camera set ups use `MP42` codec and have between `20GB` - `100GB`. On these we can not load for annotation:

<img width="517" alt="Screenshot 2022-11-25 at 12 33 24" src="https://user-images.githubusercontent.com/119053196/203986961-c54f10f5-452f-4930-b2eb-a6a7054d0df4.png">

Has there been previous reports/issues with `MP42` codec? can this be a file size issue?
Thank you.
